services:
  - type: web
    name: aman-panel
    env: docker
    region: oregon
    buildCommand: docker build -t aman-panel .
    startCommand: php -S 0.0.0.0:8080 -t /var/www/html router.php
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: app.baseURL
        value: https://aman-panel-1.onrender.com/
      - key: database.default.hostname
        value: dpg-d6dfkdhr0fns73cqksj0-a.oregon-postgres.render.com
      - key: database.default.database
        value: aman_panel
      - key: database.default.username
        value: aman_panel_user
      - key: database.default.password
        value: zlthHrxOudcWpNiucw6vYBTZRTAYhhaw
      - key: database.default.DBDriver
        value: Postgre
      - key: database.default.port
        value: 5432
